
FROM node:24 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build



FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY /nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder --chown=nginx:nginx /app/dist ./usr/share/nginx/html/

CMD ["nginx", "-g", "daemon off;"]
